# Generated by Django 4.0.1 on 2023-04-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('str_style', models.CharField(blank=True, max_length=255, null=True)),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebApp.style')),
            ],
        ),
    ]
