# Generated by Django 4.0.1 on 2023-04-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
